language: java
jdk:
  - openjdk11

services:
  - docker

before_install:
  - docker pull yandex/clickhouse-server
  - docker run -d --name some-clickhouse-server -p 8123:8123 --ulimit nofile=262144:262144 yandex/clickhouse-server

cache:
  directories:
    - "$HOME/.m2/repository"

script: mvn clean test -DtrimStackTrace=false -DuseFile=false

after_success:
  - mvn clean test jacoco:report coveralls:report